### ISSUE TITLE
Add OpenScore: lieder and (new) string quartets

### ISSUE THREAD

**Issue by MarkGotham** [apacha/OMR-Datasets#8]
Hi @apacha , all,

Thanks for this awesome repo!

- You know (and other visitors here may know) the [OpenScore Lieder collection (>1,300 19th C songs)](https://github.com/OpenScore/Lieder).
- We have now released a new collection of [String Quartets](https://github.com/OpenScore/StringQuartets). Paper coming soon to DLfM 2023.

In both cases, the IMSLP sources are listed, partly for prospective uses in OMR, so perhaps they warrant including here? I'm open to collaborations wrt OMR on those datasets if you're interested. Related, I have in mind the forthcoming MuseScore v4.2 direct export to MEI in mind as a good time to revisit this (the more so given MEI-friend).

**Comment by apacha** [comment]
Thanks for the links. I've updated the website to feature both datasets. As soon as there is the DLfM paper ready, let me know and I will update the scientific publication.
I'm also mirroring the datasets (as all others) with a snapshot of today for convenient download via the `omrdatasettools`.

**Comment by MarkGotham** [comment]
Great, thanks @apacha . I now have the DOI/URL:
https://dl.acm.org/doi/10.1145/3625135.3625155

**Comment by apacha** [comment]
Updated.
